import "@/global.css";
import Header from "./components/Header";

export const metadata = {
  title: "Cypher Notes | Space for your thoughts",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="cy_main">{children}</main>
      </body>
    </html>
  );
}
